export { fetchPages } from './pagesAction'
export { fetchHeader } from './headerAction'
export { fetchFooter } from './footerAction'
export { toggleMenu } from './menuAction'
export { fetchPrices } from './pricesAction'